<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Endpoint;

class ScanPoliciesDelete extends \Jane\OpenApiRuntime\Client\BaseEndpoint implements \Jane\OpenApiRuntime\Client\Psr7HttplugEndpoint
{
    /**
     * @param string $name the scan policy name
     */
    public function __construct(string $name)
    {
        $this->body = $name;
    }

    use \Jane\OpenApiRuntime\Client\Psr7HttplugEndpointTrait;

    public function getMethod(): string
    {
        return 'POST';
    }

    public function getUri(): string
    {
        return '/api/1.0/scanpolicies/delete';
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, \Http\Message\StreamFactory $streamFactory = null): array
    {
        return $this->getSerializedBody($serializer);
    }

    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    /**
     * {@inheritdoc}
     *
     * @throws \Montross50\NetsparkerCloud\SDK\Exception\ScanPoliciesDeleteBadRequestException
     * @throws \Montross50\NetsparkerCloud\SDK\Exception\ScanPoliciesDeleteNotFoundException
     */
    protected function transformResponseBody(string $body, int $status, \Symfony\Component\Serializer\SerializerInterface $serializer)
    {
        if (200 === $status) {
            return null;
        }
        if (400 === $status) {
            throw new \Montross50\NetsparkerCloud\SDK\Exception\ScanPoliciesDeleteBadRequestException();
        }
        if (404 === $status) {
            throw new \Montross50\NetsparkerCloud\SDK\Exception\ScanPoliciesDeleteNotFoundException();
        }
    }
}
