<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class BasicAuthenticationCredentialModelNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Montross50\\NetsparkerCloud\\SDK\\Model\\BasicAuthenticationCredentialModel';
    }

    public function supportsNormalization($data, $format = null)
    {
        return $data instanceof \Montross50\NetsparkerCloud\SDK\Model\BasicAuthenticationCredentialModel;
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Montross50\NetsparkerCloud\SDK\Model\BasicAuthenticationCredentialModel();
        if (property_exists($data, 'AuthenticationType')) {
            $object->setAuthenticationType($data->{'AuthenticationType'});
        }
        if (property_exists($data, 'Domain')) {
            $object->setDomain($data->{'Domain'});
        }
        if (property_exists($data, 'Password')) {
            $object->setPassword($data->{'Password'});
        }
        if (property_exists($data, 'UriPrefix')) {
            $object->setUriPrefix($data->{'UriPrefix'});
        }
        if (property_exists($data, 'UserName')) {
            $object->setUserName($data->{'UserName'});
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getAuthenticationType()) {
            $data->{'AuthenticationType'} = $object->getAuthenticationType();
        }
        if (null !== $object->getDomain()) {
            $data->{'Domain'} = $object->getDomain();
        }
        if (null !== $object->getPassword()) {
            $data->{'Password'} = $object->getPassword();
        }
        if (null !== $object->getUriPrefix()) {
            $data->{'UriPrefix'} = $object->getUriPrefix();
        }
        if (null !== $object->getUserName()) {
            $data->{'UserName'} = $object->getUserName();
        }

        return $data;
    }
}
