<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class BasicAuthenticationSettingModelNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Montross50\\NetsparkerCloud\\SDK\\Model\\BasicAuthenticationSettingModel';
    }

    public function supportsNormalization($data, $format = null)
    {
        return $data instanceof \Montross50\NetsparkerCloud\SDK\Model\BasicAuthenticationSettingModel;
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Montross50\NetsparkerCloud\SDK\Model\BasicAuthenticationSettingModel();
        if (property_exists($data, 'Credentials')) {
            $values = [];
            foreach ($data->{'Credentials'} as $value) {
                $values[] = $this->denormalizer->denormalize($value, 'Montross50\\NetsparkerCloud\\SDK\\Model\\BasicAuthenticationCredentialModel', 'json', $context);
            }
            $object->setCredentials($values);
        }
        if (property_exists($data, 'IsEnabled')) {
            $object->setIsEnabled($data->{'IsEnabled'});
        }
        if (property_exists($data, 'NoChallenge')) {
            $object->setNoChallenge($data->{'NoChallenge'});
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getCredentials()) {
            $values = [];
            foreach ($object->getCredentials() as $value) {
                $values[] = $this->normalizer->normalize($value, 'json', $context);
            }
            $data->{'Credentials'} = $values;
        }
        if (null !== $object->getIsEnabled()) {
            $data->{'IsEnabled'} = $object->getIsEnabled();
        }
        if (null !== $object->getNoChallenge()) {
            $data->{'NoChallenge'} = $object->getNoChallenge();
        }

        return $data;
    }
}
