<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class CrawlingSettingModelNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Montross50\\NetsparkerCloud\\SDK\\Model\\CrawlingSettingModel';
    }

    public function supportsNormalization($data, $format = null)
    {
        return $data instanceof \Montross50\NetsparkerCloud\SDK\Model\CrawlingSettingModel;
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Montross50\NetsparkerCloud\SDK\Model\CrawlingSettingModel();
        if (property_exists($data, 'EnableParameterBasedNavigation')) {
            $object->setEnableParameterBasedNavigation($data->{'EnableParameterBasedNavigation'});
        }
        if (property_exists($data, 'EnableRestWebServiceParser')) {
            $object->setEnableRestWebServiceParser($data->{'EnableRestWebServiceParser'});
        }
        if (property_exists($data, 'EnableSoapWebServiceParser')) {
            $object->setEnableSoapWebServiceParser($data->{'EnableSoapWebServiceParser'});
        }
        if (property_exists($data, 'EnableTextParser')) {
            $object->setEnableTextParser($data->{'EnableTextParser'});
        }
        if (property_exists($data, 'FallbackToGet')) {
            $object->setFallbackToGet($data->{'FallbackToGet'});
        }
        if (property_exists($data, 'FileExtensions')) {
            $object->setFileExtensions($data->{'FileExtensions'});
        }
        if (property_exists($data, 'MaximumCrawlerUrlCount')) {
            $object->setMaximumCrawlerUrlCount($data->{'MaximumCrawlerUrlCount'});
        }
        if (property_exists($data, 'MaximumSignature')) {
            $object->setMaximumSignature($data->{'MaximumSignature'});
        }
        if (property_exists($data, 'NavigationParameterPageVisitLimit')) {
            $object->setNavigationParameterPageVisitLimit($data->{'NavigationParameterPageVisitLimit'});
        }
        if (property_exists($data, 'NavigationParameterRegexPattern')) {
            $object->setNavigationParameterRegexPattern($data->{'NavigationParameterRegexPattern'});
        }
        if (property_exists($data, 'PageVisitLimit')) {
            $object->setPageVisitLimit($data->{'PageVisitLimit'});
        }
        if (property_exists($data, 'WaitResourceFinder')) {
            $object->setWaitResourceFinder($data->{'WaitResourceFinder'});
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getEnableParameterBasedNavigation()) {
            $data->{'EnableParameterBasedNavigation'} = $object->getEnableParameterBasedNavigation();
        }
        if (null !== $object->getEnableRestWebServiceParser()) {
            $data->{'EnableRestWebServiceParser'} = $object->getEnableRestWebServiceParser();
        }
        if (null !== $object->getEnableSoapWebServiceParser()) {
            $data->{'EnableSoapWebServiceParser'} = $object->getEnableSoapWebServiceParser();
        }
        if (null !== $object->getEnableTextParser()) {
            $data->{'EnableTextParser'} = $object->getEnableTextParser();
        }
        if (null !== $object->getFallbackToGet()) {
            $data->{'FallbackToGet'} = $object->getFallbackToGet();
        }
        if (null !== $object->getFileExtensions()) {
            $data->{'FileExtensions'} = $object->getFileExtensions();
        }
        if (null !== $object->getMaximumCrawlerUrlCount()) {
            $data->{'MaximumCrawlerUrlCount'} = $object->getMaximumCrawlerUrlCount();
        }
        if (null !== $object->getMaximumSignature()) {
            $data->{'MaximumSignature'} = $object->getMaximumSignature();
        }
        if (null !== $object->getNavigationParameterPageVisitLimit()) {
            $data->{'NavigationParameterPageVisitLimit'} = $object->getNavigationParameterPageVisitLimit();
        }
        if (null !== $object->getNavigationParameterRegexPattern()) {
            $data->{'NavigationParameterRegexPattern'} = $object->getNavigationParameterRegexPattern();
        }
        if (null !== $object->getPageVisitLimit()) {
            $data->{'PageVisitLimit'} = $object->getPageVisitLimit();
        }
        if (null !== $object->getWaitResourceFinder()) {
            $data->{'WaitResourceFinder'} = $object->getWaitResourceFinder();
        }

        return $data;
    }
}
