<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class FormAuthenticationVerificationApiModelNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Montross50\\NetsparkerCloud\\SDK\\Model\\FormAuthenticationVerificationApiModel';
    }

    public function supportsNormalization($data, $format = null)
    {
        return $data instanceof \Montross50\NetsparkerCloud\SDK\Model\FormAuthenticationVerificationApiModel;
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Montross50\NetsparkerCloud\SDK\Model\FormAuthenticationVerificationApiModel();
        if (property_exists($data, 'LoginFormUrl')) {
            $object->setLoginFormUrl($data->{'LoginFormUrl'});
        }
        if (property_exists($data, 'Password')) {
            $object->setPassword($data->{'Password'});
        }
        if (property_exists($data, 'ScanTargetUrl')) {
            $object->setScanTargetUrl($data->{'ScanTargetUrl'});
        }
        if (property_exists($data, 'Username')) {
            $object->setUsername($data->{'Username'});
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getLoginFormUrl()) {
            $data->{'LoginFormUrl'} = $object->getLoginFormUrl();
        }
        if (null !== $object->getPassword()) {
            $data->{'Password'} = $object->getPassword();
        }
        if (null !== $object->getScanTargetUrl()) {
            $data->{'ScanTargetUrl'} = $object->getScanTargetUrl();
        }
        if (null !== $object->getUsername()) {
            $data->{'Username'} = $object->getUsername();
        }

        return $data;
    }
}
