<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class ScopeSettingNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Montross50\\NetsparkerCloud\\SDK\\Model\\ScopeSetting';
    }

    public function supportsNormalization($data, $format = null)
    {
        return $data instanceof \Montross50\NetsparkerCloud\SDK\Model\ScopeSetting;
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Montross50\NetsparkerCloud\SDK\Model\ScopeSetting();
        if (property_exists($data, 'ExcludedLinks')) {
            $values = [];
            foreach ($data->{'ExcludedLinks'} as $value) {
                $values[] = $this->denormalizer->denormalize($value, 'Montross50\\NetsparkerCloud\\SDK\\Model\\ExcludedLinkModel', 'json', $context);
            }
            $object->setExcludedLinks($values);
        }
        if (property_exists($data, 'ExcludeLinks')) {
            $object->setExcludeLinks($data->{'ExcludeLinks'});
        }
        if (property_exists($data, 'DisallowedHttpMethods')) {
            $values_1 = [];
            foreach ($data->{'DisallowedHttpMethods'} as $value_1) {
                $values_1[] = $value_1;
            }
            $object->setDisallowedHttpMethods($values_1);
        }
        if (property_exists($data, 'Scope')) {
            $object->setScope($data->{'Scope'});
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getExcludedLinks()) {
            $values = [];
            foreach ($object->getExcludedLinks() as $value) {
                $values[] = $this->normalizer->normalize($value, 'json', $context);
            }
            $data->{'ExcludedLinks'} = $values;
        }
        if (null !== $object->getExcludeLinks()) {
            $data->{'ExcludeLinks'} = $object->getExcludeLinks();
        }
        if (null !== $object->getDisallowedHttpMethods()) {
            $values_1 = [];
            foreach ($object->getDisallowedHttpMethods() as $value_1) {
                $values_1[] = $value_1;
            }
            $data->{'DisallowedHttpMethods'} = $values_1;
        }
        if (null !== $object->getScope()) {
            $data->{'Scope'} = $object->getScope();
        }

        return $data;
    }
}
