<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class AgentGroupApiUpdateModel
{
    /**
     * Agents ids.
     *
     * @var string[]
     */
    protected $agents;
    /**
     * The identifier.
     *
     * @var string
     */
    protected $id;
    /**
     * The agent group name.
     *
     * @var string
     */
    protected $name;

    /**
     * Agents ids.
     *
     * @return string[]
     */
    public function getAgents(): ?array
    {
        return $this->agents;
    }

    /**
     * Agents ids.
     *
     * @param string[] $agents
     *
     * @return self
     */
    public function setAgents(?array $agents): self
    {
        $this->agents = $agents;

        return $this;
    }

    /**
     * The identifier.
     *
     * @return string
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * The identifier.
     *
     * @param string $id
     *
     * @return self
     */
    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * The agent group name.
     *
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * The agent group name.
     *
     * @param string $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
}
