<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class BasicAuthenticationSettingModel
{
    /**
     * Gets or sets the authentication credentials.
     *
     * @var BasicAuthenticationCredentialModel[]
     */
    protected $credentials;
    /**
     * Gets or sets a value indicating whether basic authentication is enabled.
     *
     * @var bool
     */
    protected $isEnabled;
    /**
     * Gets or sets a value indicating whether to send authentication headers without expecting a challenge.
     *
     * @var bool
     */
    protected $noChallenge;

    /**
     * Gets or sets the authentication credentials.
     *
     * @return BasicAuthenticationCredentialModel[]
     */
    public function getCredentials(): ?array
    {
        return $this->credentials;
    }

    /**
     * Gets or sets the authentication credentials.
     *
     * @param BasicAuthenticationCredentialModel[] $credentials
     *
     * @return self
     */
    public function setCredentials(?array $credentials): self
    {
        $this->credentials = $credentials;

        return $this;
    }

    /**
     * Gets or sets a value indicating whether basic authentication is enabled.
     *
     * @return bool
     */
    public function getIsEnabled(): ?bool
    {
        return $this->isEnabled;
    }

    /**
     * Gets or sets a value indicating whether basic authentication is enabled.
     *
     * @param bool $isEnabled
     *
     * @return self
     */
    public function setIsEnabled(?bool $isEnabled): self
    {
        $this->isEnabled = $isEnabled;

        return $this;
    }

    /**
     * Gets or sets a value indicating whether to send authentication headers without expecting a challenge.
     *
     * @return bool
     */
    public function getNoChallenge(): ?bool
    {
        return $this->noChallenge;
    }

    /**
     * Gets or sets a value indicating whether to send authentication headers without expecting a challenge.
     *
     * @param bool $noChallenge
     *
     * @return self
     */
    public function setNoChallenge(?bool $noChallenge): self
    {
        $this->noChallenge = $noChallenge;

        return $this;
    }
}
