<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class BruteForceSettingModel
{
    /**
     * Gets or sets a value indicating whether authentication brute force should be enabled.
     *
     * @var bool
     */
    protected $enableAuthBruteForce;
    /**
     * Gets or sets the maximum brute force count.
     *
     * @var int
     */
    protected $maxBruteForce;

    /**
     * Gets or sets a value indicating whether authentication brute force should be enabled.
     *
     * @return bool
     */
    public function getEnableAuthBruteForce(): ?bool
    {
        return $this->enableAuthBruteForce;
    }

    /**
     * Gets or sets a value indicating whether authentication brute force should be enabled.
     *
     * @param bool $enableAuthBruteForce
     *
     * @return self
     */
    public function setEnableAuthBruteForce(?bool $enableAuthBruteForce): self
    {
        $this->enableAuthBruteForce = $enableAuthBruteForce;

        return $this;
    }

    /**
     * Gets or sets the maximum brute force count.
     *
     * @return int
     */
    public function getMaxBruteForce(): ?int
    {
        return $this->maxBruteForce;
    }

    /**
     * Gets or sets the maximum brute force count.
     *
     * @param int $maxBruteForce
     *
     * @return self
     */
    public function setMaxBruteForce(?int $maxBruteForce): self
    {
        $this->maxBruteForce = $maxBruteForce;

        return $this;
    }
}
