<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class ClientCertificateAuthenticationApiModel
{
    /**
     * Represents a model for file.
     *
     * @var ApiFileModel
     */
    protected $file;
    /**
     * Gets or sets a value indicating whether client certificate authentication is enabled.
     *
     * @var bool
     */
    protected $isEnabled;
    /**
     * Gets or sets the password for client certificate authentication.
     *
     * @var string
     */
    protected $password;

    /**
     * Represents a model for file.
     *
     * @return ApiFileModel
     */
    public function getFile(): ?ApiFileModel
    {
        return $this->file;
    }

    /**
     * Represents a model for file.
     *
     * @param ApiFileModel $file
     *
     * @return self
     */
    public function setFile(?ApiFileModel $file): self
    {
        $this->file = $file;

        return $this;
    }

    /**
     * Gets or sets a value indicating whether client certificate authentication is enabled.
     *
     * @return bool
     */
    public function getIsEnabled(): ?bool
    {
        return $this->isEnabled;
    }

    /**
     * Gets or sets a value indicating whether client certificate authentication is enabled.
     *
     * @param bool $isEnabled
     *
     * @return self
     */
    public function setIsEnabled(?bool $isEnabled): self
    {
        $this->isEnabled = $isEnabled;

        return $this;
    }

    /**
     * Gets or sets the password for client certificate authentication.
     *
     * @return string
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * Gets or sets the password for client certificate authentication.
     *
     * @param string $password
     *
     * @return self
     */
    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }
}
