<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class CsrfSettingModel
{
    /**
     * A list of values which is used to check a form contains captcha against CSRF.
     *
     * @var string
     */
    protected $captchaIndicators;
    /**
     * A list of values to indicate login forms whose submit inputs' name or value contains one of these.
     *
     * @var string
     */
    protected $loginFormValues;
    /**
     * A list of values to indicate non-CSRF forms whose name or action contains one of these.
     *
     * @var string
     */
    protected $nonFormValues;
    /**
     * A list of values to indicate non-CSRF forms in which input's name or value contains one of these.
     *
     * @var string
     */
    protected $nonInputValues;
    /**
     * A list of values to indicate username inputs whose name includes one of these.
     *
     * @var string
     */
    protected $userNameInputs;

    /**
     * A list of values which is used to check a form contains captcha against CSRF.
     *
     * @return string
     */
    public function getCaptchaIndicators(): ?string
    {
        return $this->captchaIndicators;
    }

    /**
     * A list of values which is used to check a form contains captcha against CSRF.
     *
     * @param string $captchaIndicators
     *
     * @return self
     */
    public function setCaptchaIndicators(?string $captchaIndicators): self
    {
        $this->captchaIndicators = $captchaIndicators;

        return $this;
    }

    /**
     * A list of values to indicate login forms whose submit inputs' name or value contains one of these.
     *
     * @return string
     */
    public function getLoginFormValues(): ?string
    {
        return $this->loginFormValues;
    }

    /**
     * A list of values to indicate login forms whose submit inputs' name or value contains one of these.
     *
     * @param string $loginFormValues
     *
     * @return self
     */
    public function setLoginFormValues(?string $loginFormValues): self
    {
        $this->loginFormValues = $loginFormValues;

        return $this;
    }

    /**
     * A list of values to indicate non-CSRF forms whose name or action contains one of these.
     *
     * @return string
     */
    public function getNonFormValues(): ?string
    {
        return $this->nonFormValues;
    }

    /**
     * A list of values to indicate non-CSRF forms whose name or action contains one of these.
     *
     * @param string $nonFormValues
     *
     * @return self
     */
    public function setNonFormValues(?string $nonFormValues): self
    {
        $this->nonFormValues = $nonFormValues;

        return $this;
    }

    /**
     * A list of values to indicate non-CSRF forms in which input's name or value contains one of these.
     *
     * @return string
     */
    public function getNonInputValues(): ?string
    {
        return $this->nonInputValues;
    }

    /**
     * A list of values to indicate non-CSRF forms in which input's name or value contains one of these.
     *
     * @param string $nonInputValues
     *
     * @return self
     */
    public function setNonInputValues(?string $nonInputValues): self
    {
        $this->nonInputValues = $nonInputValues;

        return $this;
    }

    /**
     * A list of values to indicate username inputs whose name includes one of these.
     *
     * @return string
     */
    public function getUserNameInputs(): ?string
    {
        return $this->userNameInputs;
    }

    /**
     * A list of values to indicate username inputs whose name includes one of these.
     *
     * @param string $userNameInputs
     *
     * @return self
     */
    public function setUserNameInputs(?string $userNameInputs): self
    {
        $this->userNameInputs = $userNameInputs;

        return $this;
    }
}
