<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class DeleteWebsiteApiModel
{
    /**
     * Gets or sets the root URL.
     *
     * @var string
     */
    protected $rootUrl;

    /**
     * Gets or sets the root URL.
     *
     * @return string
     */
    public function getRootUrl(): ?string
    {
        return $this->rootUrl;
    }

    /**
     * Gets or sets the root URL.
     *
     * @param string $rootUrl
     *
     * @return self
     */
    public function setRootUrl(?string $rootUrl): self
    {
        $this->rootUrl = $rootUrl;

        return $this;
    }
}
