<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class ImportedLinksSetting
{
    /**
     * Gets or sets the imported files.
     *
     * @var FileCache[]
     */
    protected $importedFiles;
    /**
     * Gets or sets the imported links.
     *
     * @var string
     */
    protected $importedLinks;

    /**
     * Gets or sets the imported files.
     *
     * @return FileCache[]
     */
    public function getImportedFiles(): ?array
    {
        return $this->importedFiles;
    }

    /**
     * Gets or sets the imported files.
     *
     * @param FileCache[] $importedFiles
     *
     * @return self
     */
    public function setImportedFiles(?array $importedFiles): self
    {
        $this->importedFiles = $importedFiles;

        return $this;
    }

    /**
     * Gets or sets the imported links.
     *
     * @return string
     */
    public function getImportedLinks(): ?string
    {
        return $this->importedLinks;
    }

    /**
     * Gets or sets the imported links.
     *
     * @param string $importedLinks
     *
     * @return self
     */
    public function setImportedLinks(?string $importedLinks): self
    {
        $this->importedLinks = $importedLinks;

        return $this;
    }
}
