<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class NewScheduledIncrementalScanApiModel
{
    /**
     * Gets or sets a value indicating whether max scan duration is enabled.
     *
     * @var bool
     */
    protected $isMaxScanDurationEnabled;
    /**
     * Gets or sets the maximum duration of the scan in hours.
     *
     * @var int
     */
    protected $maxScanDuration;
    /**
     * Gets or sets the name.
     *
     * @var string
     */
    protected $name;
    /**
     * Gets or sets the next execution time.
    Date string must be in the same format as in the account settings.
     *
     * @var string
     */
    protected $nextExecutionTime;
    /**
     * Gets or sets the run interval of scheduled scan.
     *
     * @var string
     */
    protected $scheduleRunType;
    /**
     * Gets or sets the agent name.
     *
     * @var string
     */
    protected $agentName;
    /**
     * Gets or sets the base scan identifier.
     *
     * @var string
     */
    protected $baseScanId;

    /**
     * Gets or sets a value indicating whether max scan duration is enabled.
     *
     * @return bool
     */
    public function getIsMaxScanDurationEnabled(): ?bool
    {
        return $this->isMaxScanDurationEnabled;
    }

    /**
     * Gets or sets a value indicating whether max scan duration is enabled.
     *
     * @param bool $isMaxScanDurationEnabled
     *
     * @return self
     */
    public function setIsMaxScanDurationEnabled(?bool $isMaxScanDurationEnabled): self
    {
        $this->isMaxScanDurationEnabled = $isMaxScanDurationEnabled;

        return $this;
    }

    /**
     * Gets or sets the maximum duration of the scan in hours.
     *
     * @return int
     */
    public function getMaxScanDuration(): ?int
    {
        return $this->maxScanDuration;
    }

    /**
     * Gets or sets the maximum duration of the scan in hours.
     *
     * @param int $maxScanDuration
     *
     * @return self
     */
    public function setMaxScanDuration(?int $maxScanDuration): self
    {
        $this->maxScanDuration = $maxScanDuration;

        return $this;
    }

    /**
     * Gets or sets the name.
     *
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Gets or sets the name.
     *
     * @param string $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets or sets the next execution time.
    Date string must be in the same format as in the account settings.
     *
     * @return string
     */
    public function getNextExecutionTime(): ?string
    {
        return $this->nextExecutionTime;
    }

    /**
     * Gets or sets the next execution time.
    Date string must be in the same format as in the account settings.
     *
     * @param string $nextExecutionTime
     *
     * @return self
     */
    public function setNextExecutionTime(?string $nextExecutionTime): self
    {
        $this->nextExecutionTime = $nextExecutionTime;

        return $this;
    }

    /**
     * Gets or sets the run interval of scheduled scan.
     *
     * @return string
     */
    public function getScheduleRunType(): ?string
    {
        return $this->scheduleRunType;
    }

    /**
     * Gets or sets the run interval of scheduled scan.
     *
     * @param string $scheduleRunType
     *
     * @return self
     */
    public function setScheduleRunType(?string $scheduleRunType): self
    {
        $this->scheduleRunType = $scheduleRunType;

        return $this;
    }

    /**
     * Gets or sets the agent name.
     *
     * @return string
     */
    public function getAgentName(): ?string
    {
        return $this->agentName;
    }

    /**
     * Gets or sets the agent name.
     *
     * @param string $agentName
     *
     * @return self
     */
    public function setAgentName(?string $agentName): self
    {
        $this->agentName = $agentName;

        return $this;
    }

    /**
     * Gets or sets the base scan identifier.
     *
     * @return string
     */
    public function getBaseScanId(): ?string
    {
        return $this->baseScanId;
    }

    /**
     * Gets or sets the base scan identifier.
     *
     * @param string $baseScanId
     *
     * @return self
     */
    public function setBaseScanId(?string $baseScanId): self
    {
        $this->baseScanId = $baseScanId;

        return $this;
    }
}
