<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class NewScanTaskWithProfileApiModel
{
    /**
     * Gets or sets the profile id.
     *
     * @var string
     */
    protected $profileName;
    /**
     * Gets or sets the target URI.
     *
     * @var string
     */
    protected $targetUri;

    /**
     * Gets or sets the profile id.
     *
     * @return string
     */
    public function getProfileName(): ?string
    {
        return $this->profileName;
    }

    /**
     * Gets or sets the profile id.
     *
     * @param string $profileName
     *
     * @return self
     */
    public function setProfileName(?string $profileName): self
    {
        $this->profileName = $profileName;

        return $this;
    }

    /**
     * Gets or sets the target URI.
     *
     * @return string
     */
    public function getTargetUri(): ?string
    {
        return $this->targetUri;
    }

    /**
     * Gets or sets the target URI.
     *
     * @param string $targetUri
     *
     * @return self
     */
    public function setTargetUri(?string $targetUri): self
    {
        $this->targetUri = $targetUri;

        return $this;
    }
}
