<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class NewWebsiteApiModel
{
    /**
     * Gets or sets the root URL.
     *
     * @var string
     */
    protected $rootUrl;
    /**
     * Gets or sets the name of groups this website will belong to.
     *
     * @var string[]
     */
    protected $groups;
    /**
     * Gets or sets the type of the subscription.
     *
     * @var string
     */
    protected $licenseType;
    /**
     * Gets or sets the website name.
     *
     * @var string
     */
    protected $name;
    /**
     * Gets or sets the technical contact email.
     *
     * @var string
     */
    protected $technicalContactEmail;

    /**
     * Gets or sets the root URL.
     *
     * @return string
     */
    public function getRootUrl(): ?string
    {
        return $this->rootUrl;
    }

    /**
     * Gets or sets the root URL.
     *
     * @param string $rootUrl
     *
     * @return self
     */
    public function setRootUrl(?string $rootUrl): self
    {
        $this->rootUrl = $rootUrl;

        return $this;
    }

    /**
     * Gets or sets the name of groups this website will belong to.
     *
     * @return string[]
     */
    public function getGroups(): ?array
    {
        return $this->groups;
    }

    /**
     * Gets or sets the name of groups this website will belong to.
     *
     * @param string[] $groups
     *
     * @return self
     */
    public function setGroups(?array $groups): self
    {
        $this->groups = $groups;

        return $this;
    }

    /**
     * Gets or sets the type of the subscription.
     *
     * @return string
     */
    public function getLicenseType(): ?string
    {
        return $this->licenseType;
    }

    /**
     * Gets or sets the type of the subscription.
     *
     * @param string $licenseType
     *
     * @return self
     */
    public function setLicenseType(?string $licenseType): self
    {
        $this->licenseType = $licenseType;

        return $this;
    }

    /**
     * Gets or sets the website name.
     *
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Gets or sets the website name.
     *
     * @param string $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets or sets the technical contact email.
     *
     * @return string
     */
    public function getTechnicalContactEmail(): ?string
    {
        return $this->technicalContactEmail;
    }

    /**
     * Gets or sets the technical contact email.
     *
     * @param string $technicalContactEmail
     *
     * @return self
     */
    public function setTechnicalContactEmail(?string $technicalContactEmail): self
    {
        $this->technicalContactEmail = $technicalContactEmail;

        return $this;
    }
}
