<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class ScanNotificationRecipientApiModel
{
    /**
     * Gets or sets the users who will be notified via Email.
     *
     * @var ScanNotificationRecipientUserApiModel[]
     */
    protected $emailRecipientUsers;
    /**
     * Gets or sets the users who won't be notified.
     *
     * @var ScanNotificationRecipientUserApiModel[]
     */
    protected $excludedUsers;
    /**
     * Gets or sets the integration end points which will be notified.
     *
     * @var string[]
     */
    protected $integrationRecipients;
    /**
     * Gets or sets the users who will be notified via SMS.
     *
     * @var ScanNotificationRecipientUserApiModel[]
     */
    protected $smsRecipientUsers;
    /**
     * Gets or sets the specific recipients who will be notified via Email.
     *
     * @var string[]
     */
    protected $specificEmailRecipients;
    /**
     * Gets or sets the specific recipients who will be notified via SMS.
     *
     * @var string[]
     */
    protected $specificSmsRecipients;

    /**
     * Gets or sets the users who will be notified via Email.
     *
     * @return ScanNotificationRecipientUserApiModel[]
     */
    public function getEmailRecipientUsers(): ?array
    {
        return $this->emailRecipientUsers;
    }

    /**
     * Gets or sets the users who will be notified via Email.
     *
     * @param ScanNotificationRecipientUserApiModel[] $emailRecipientUsers
     *
     * @return self
     */
    public function setEmailRecipientUsers(?array $emailRecipientUsers): self
    {
        $this->emailRecipientUsers = $emailRecipientUsers;

        return $this;
    }

    /**
     * Gets or sets the users who won't be notified.
     *
     * @return ScanNotificationRecipientUserApiModel[]
     */
    public function getExcludedUsers(): ?array
    {
        return $this->excludedUsers;
    }

    /**
     * Gets or sets the users who won't be notified.
     *
     * @param ScanNotificationRecipientUserApiModel[] $excludedUsers
     *
     * @return self
     */
    public function setExcludedUsers(?array $excludedUsers): self
    {
        $this->excludedUsers = $excludedUsers;

        return $this;
    }

    /**
     * Gets or sets the integration end points which will be notified.
     *
     * @return string[]
     */
    public function getIntegrationRecipients(): ?array
    {
        return $this->integrationRecipients;
    }

    /**
     * Gets or sets the integration end points which will be notified.
     *
     * @param string[] $integrationRecipients
     *
     * @return self
     */
    public function setIntegrationRecipients(?array $integrationRecipients): self
    {
        $this->integrationRecipients = $integrationRecipients;

        return $this;
    }

    /**
     * Gets or sets the users who will be notified via SMS.
     *
     * @return ScanNotificationRecipientUserApiModel[]
     */
    public function getSmsRecipientUsers(): ?array
    {
        return $this->smsRecipientUsers;
    }

    /**
     * Gets or sets the users who will be notified via SMS.
     *
     * @param ScanNotificationRecipientUserApiModel[] $smsRecipientUsers
     *
     * @return self
     */
    public function setSmsRecipientUsers(?array $smsRecipientUsers): self
    {
        $this->smsRecipientUsers = $smsRecipientUsers;

        return $this;
    }

    /**
     * Gets or sets the specific recipients who will be notified via Email.
     *
     * @return string[]
     */
    public function getSpecificEmailRecipients(): ?array
    {
        return $this->specificEmailRecipients;
    }

    /**
     * Gets or sets the specific recipients who will be notified via Email.
     *
     * @param string[] $specificEmailRecipients
     *
     * @return self
     */
    public function setSpecificEmailRecipients(?array $specificEmailRecipients): self
    {
        $this->specificEmailRecipients = $specificEmailRecipients;

        return $this;
    }

    /**
     * Gets or sets the specific recipients who will be notified via SMS.
     *
     * @return string[]
     */
    public function getSpecificSmsRecipients(): ?array
    {
        return $this->specificSmsRecipients;
    }

    /**
     * Gets or sets the specific recipients who will be notified via SMS.
     *
     * @param string[] $specificSmsRecipients
     *
     * @return self
     */
    public function setSpecificSmsRecipients(?array $specificSmsRecipients): self
    {
        $this->specificSmsRecipients = $specificSmsRecipients;

        return $this;
    }
}
