<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class ScanTimeWindowModel
{
    /**
     * Gets or sets the time range items.
     *
     * @var ScanTimeWindowItemModel[]
     */
    protected $items;

    /**
     * Gets or sets the time range items.
     *
     * @return ScanTimeWindowItemModel[]
     */
    public function getItems(): ?array
    {
        return $this->items;
    }

    /**
     * Gets or sets the time range items.
     *
     * @param ScanTimeWindowItemModel[] $items
     *
     * @return self
     */
    public function setItems(?array $items): self
    {
        $this->items = $items;

        return $this;
    }
}
