<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class ScanPolicyPatternModel
{
    /**
     * Gets or sets the description of the security check.
     *
     * @var string
     */
    protected $description;
    /**
     * Gets or sets a value indicating whether this instance is enabled.
     *
     * @var bool
     */
    protected $enabled;
    /**
     * Gets or sets the id of the security check.
     *
     * @var string
     */
    protected $id;
    /**
     * Gets or sets the name of the security check.
     *
     * @var string
     */
    protected $name;

    /**
     * Gets or sets the description of the security check.
     *
     * @return string
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Gets or sets the description of the security check.
     *
     * @param string $description
     *
     * @return self
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Gets or sets a value indicating whether this instance is enabled.
     *
     * @return bool
     */
    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    /**
     * Gets or sets a value indicating whether this instance is enabled.
     *
     * @param bool $enabled
     *
     * @return self
     */
    public function setEnabled(?bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * Gets or sets the id of the security check.
     *
     * @return string
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Gets or sets the id of the security check.
     *
     * @param string $id
     *
     * @return self
     */
    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets or sets the name of the security check.
     *
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Gets or sets the name of the security check.
     *
     * @param string $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
}
