<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class ScanPolicyOptimizerOptions
{
    /**
     * @var string
     */
    protected $appServer;
    /**
     * @var string
     */
    protected $databaseServer;
    /**
     * @var int
     */
    protected $directoryNameLimit;
    /**
     * @var string
     */
    protected $domParserPreset;
    /**
     * @var string
     */
    protected $name;
    /**
     * @var string
     */
    protected $netsparkerHawkBaseUrl;
    /**
     * @var string
     */
    protected $operatingSystem;
    /**
     * @var bool
     */
    protected $optimized;
    /**
     * @var string[]
     */
    protected $resourceFinders;
    /**
     * @var string
     */
    protected $suggestionStatus;
    /**
     * @var string
     */
    protected $webServer;

    /**
     * @return string
     */
    public function getAppServer(): ?string
    {
        return $this->appServer;
    }

    /**
     * @param string $appServer
     *
     * @return self
     */
    public function setAppServer(?string $appServer): self
    {
        $this->appServer = $appServer;

        return $this;
    }

    /**
     * @return string
     */
    public function getDatabaseServer(): ?string
    {
        return $this->databaseServer;
    }

    /**
     * @param string $databaseServer
     *
     * @return self
     */
    public function setDatabaseServer(?string $databaseServer): self
    {
        $this->databaseServer = $databaseServer;

        return $this;
    }

    /**
     * @return int
     */
    public function getDirectoryNameLimit(): ?int
    {
        return $this->directoryNameLimit;
    }

    /**
     * @param int $directoryNameLimit
     *
     * @return self
     */
    public function setDirectoryNameLimit(?int $directoryNameLimit): self
    {
        $this->directoryNameLimit = $directoryNameLimit;

        return $this;
    }

    /**
     * @return string
     */
    public function getDomParserPreset(): ?string
    {
        return $this->domParserPreset;
    }

    /**
     * @param string $domParserPreset
     *
     * @return self
     */
    public function setDomParserPreset(?string $domParserPreset): self
    {
        $this->domParserPreset = $domParserPreset;

        return $this;
    }

    /**
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string
     */
    public function getNetsparkerHawkBaseUrl(): ?string
    {
        return $this->netsparkerHawkBaseUrl;
    }

    /**
     * @param string $netsparkerHawkBaseUrl
     *
     * @return self
     */
    public function setNetsparkerHawkBaseUrl(?string $netsparkerHawkBaseUrl): self
    {
        $this->netsparkerHawkBaseUrl = $netsparkerHawkBaseUrl;

        return $this;
    }

    /**
     * @return string
     */
    public function getOperatingSystem(): ?string
    {
        return $this->operatingSystem;
    }

    /**
     * @param string $operatingSystem
     *
     * @return self
     */
    public function setOperatingSystem(?string $operatingSystem): self
    {
        $this->operatingSystem = $operatingSystem;

        return $this;
    }

    /**
     * @return bool
     */
    public function getOptimized(): ?bool
    {
        return $this->optimized;
    }

    /**
     * @param bool $optimized
     *
     * @return self
     */
    public function setOptimized(?bool $optimized): self
    {
        $this->optimized = $optimized;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getResourceFinders(): ?array
    {
        return $this->resourceFinders;
    }

    /**
     * @param string[] $resourceFinders
     *
     * @return self
     */
    public function setResourceFinders(?array $resourceFinders): self
    {
        $this->resourceFinders = $resourceFinders;

        return $this;
    }

    /**
     * @return string
     */
    public function getSuggestionStatus(): ?string
    {
        return $this->suggestionStatus;
    }

    /**
     * @param string $suggestionStatus
     *
     * @return self
     */
    public function setSuggestionStatus(?string $suggestionStatus): self
    {
        $this->suggestionStatus = $suggestionStatus;

        return $this;
    }

    /**
     * @return string
     */
    public function getWebServer(): ?string
    {
        return $this->webServer;
    }

    /**
     * @param string $webServer
     *
     * @return self
     */
    public function setWebServer(?string $webServer): self
    {
        $this->webServer = $webServer;

        return $this;
    }
}
