<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class ScanTimeWindowItemModel
{
    /**
     * Gets or sets the day.
     *
     * @var string
     */
    protected $day;
    /**
     * Gets or sets the left side of the time range.
    Default: 00:00
     *
     * @var string
     */
    protected $from;
    /**
     * Gets or sets a value indicating whether scanning is allowed or not.
    Default: true
     *
     * @var bool
     */
    protected $scanningAllowed;
    /**
     * Gets or sets the right side of the time range.
    Default: 23:59
     *
     * @var string
     */
    protected $to;

    /**
     * Gets or sets the day.
     *
     * @return string
     */
    public function getDay(): ?string
    {
        return $this->day;
    }

    /**
     * Gets or sets the day.
     *
     * @param string $day
     *
     * @return self
     */
    public function setDay(?string $day): self
    {
        $this->day = $day;

        return $this;
    }

    /**
     * Gets or sets the left side of the time range.
    Default: 00:00
     *
     * @return string
     */
    public function getFrom(): ?string
    {
        return $this->from;
    }

    /**
     * Gets or sets the left side of the time range.
    Default: 00:00
     *
     * @param string $from
     *
     * @return self
     */
    public function setFrom(?string $from): self
    {
        $this->from = $from;

        return $this;
    }

    /**
     * Gets or sets a value indicating whether scanning is allowed or not.
    Default: true
     *
     * @return bool
     */
    public function getScanningAllowed(): ?bool
    {
        return $this->scanningAllowed;
    }

    /**
     * Gets or sets a value indicating whether scanning is allowed or not.
    Default: true
     *
     * @param bool $scanningAllowed
     *
     * @return self
     */
    public function setScanningAllowed(?bool $scanningAllowed): self
    {
        $this->scanningAllowed = $scanningAllowed;

        return $this;
    }

    /**
     * Gets or sets the right side of the time range.
    Default: 23:59
     *
     * @return string
     */
    public function getTo(): ?string
    {
        return $this->to;
    }

    /**
     * Gets or sets the right side of the time range.
    Default: 23:59
     *
     * @param string $to
     *
     * @return self
     */
    public function setTo(?string $to): self
    {
        $this->to = $to;

        return $this;
    }
}
