<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class SecurityCheckGroupModel
{
    /**
     * Gets or sets the scan policy patterns.
     *
     * @var ScanPolicyPatternModel[]
     */
    protected $patterns;
    /**
     * Gets or sets the settings.
     *
     * @var SecurityCheckSetting[]
     */
    protected $settings;
    /**
     * Gets or sets the security check group type.
     *
     * @var string
     */
    protected $type;
    /**
     * Gets or sets the description of the security check.
     *
     * @var string
     */
    protected $description;
    /**
     * Gets or sets a value indicating whether this instance is enabled.
     *
     * @var bool
     */
    protected $enabled;
    /**
     * Gets or sets the id of the security check.
     *
     * @var string
     */
    protected $id;
    /**
     * Gets or sets the name of the security check.
     *
     * @var string
     */
    protected $name;

    /**
     * Gets or sets the scan policy patterns.
     *
     * @return ScanPolicyPatternModel[]
     */
    public function getPatterns(): ?array
    {
        return $this->patterns;
    }

    /**
     * Gets or sets the scan policy patterns.
     *
     * @param ScanPolicyPatternModel[] $patterns
     *
     * @return self
     */
    public function setPatterns(?array $patterns): self
    {
        $this->patterns = $patterns;

        return $this;
    }

    /**
     * Gets or sets the settings.
     *
     * @return SecurityCheckSetting[]
     */
    public function getSettings(): ?array
    {
        return $this->settings;
    }

    /**
     * Gets or sets the settings.
     *
     * @param SecurityCheckSetting[] $settings
     *
     * @return self
     */
    public function setSettings(?array $settings): self
    {
        $this->settings = $settings;

        return $this;
    }

    /**
     * Gets or sets the security check group type.
     *
     * @return string
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Gets or sets the security check group type.
     *
     * @param string $type
     *
     * @return self
     */
    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Gets or sets the description of the security check.
     *
     * @return string
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Gets or sets the description of the security check.
     *
     * @param string $description
     *
     * @return self
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Gets or sets a value indicating whether this instance is enabled.
     *
     * @return bool
     */
    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    /**
     * Gets or sets a value indicating whether this instance is enabled.
     *
     * @param bool $enabled
     *
     * @return self
     */
    public function setEnabled(?bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * Gets or sets the id of the security check.
     *
     * @return string
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Gets or sets the id of the security check.
     *
     * @param string $id
     *
     * @return self
     */
    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets or sets the name of the security check.
     *
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Gets or sets the name of the security check.
     *
     * @param string $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
}
