<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class SendVerificationEmailModel
{
    /**
     * Gets or sets a value indicating whether sent verification email.
     *
     * @var bool
     */
    protected $isMailSent;
    /**
     * Gets or sets a value indicating message of verification.
     *
     * @var string
     */
    protected $verificationMessage;

    /**
     * Gets or sets a value indicating whether sent verification email.
     *
     * @return bool
     */
    public function getIsMailSent(): ?bool
    {
        return $this->isMailSent;
    }

    /**
     * Gets or sets a value indicating whether sent verification email.
     *
     * @param bool $isMailSent
     *
     * @return self
     */
    public function setIsMailSent(?bool $isMailSent): self
    {
        $this->isMailSent = $isMailSent;

        return $this;
    }

    /**
     * Gets or sets a value indicating message of verification.
     *
     * @return string
     */
    public function getVerificationMessage(): ?string
    {
        return $this->verificationMessage;
    }

    /**
     * Gets or sets a value indicating message of verification.
     *
     * @param string $verificationMessage
     *
     * @return self
     */
    public function setVerificationMessage(?string $verificationMessage): self
    {
        $this->verificationMessage = $verificationMessage;

        return $this;
    }
}
