<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class SslTlsSettingModel
{
    /**
     * Gets or sets invalid certificate action for the external domains.
     *
     * @var string
     */
    protected $externalDomainInvalidCertificateAction;
    /**
     * Gets or sets a value indicating whether SSL v3 is enabled.
     *
     * @var bool
     */
    protected $ssl3Enabled;
    /**
     * Gets or sets invalid certificate action for the target URL.
     *
     * @var string
     */
    protected $targetUrlInvalidCertificateAction;
    /**
     * Gets or sets a value indicating whether TLS 1.0 is enabled.
     *
     * @var bool
     */
    protected $tls10Enabled;
    /**
     * Gets or sets a value indicating whether TLS 1.1 is enabled.
     *
     * @var bool
     */
    protected $tls11Enabled;
    /**
     * Gets or sets a value indicating whether TLS 1.2 is enabled.
     *
     * @var bool
     */
    protected $tls12Enabled;

    /**
     * Gets or sets invalid certificate action for the external domains.
     *
     * @return string
     */
    public function getExternalDomainInvalidCertificateAction(): ?string
    {
        return $this->externalDomainInvalidCertificateAction;
    }

    /**
     * Gets or sets invalid certificate action for the external domains.
     *
     * @param string $externalDomainInvalidCertificateAction
     *
     * @return self
     */
    public function setExternalDomainInvalidCertificateAction(?string $externalDomainInvalidCertificateAction): self
    {
        $this->externalDomainInvalidCertificateAction = $externalDomainInvalidCertificateAction;

        return $this;
    }

    /**
     * Gets or sets a value indicating whether SSL v3 is enabled.
     *
     * @return bool
     */
    public function getSsl3Enabled(): ?bool
    {
        return $this->ssl3Enabled;
    }

    /**
     * Gets or sets a value indicating whether SSL v3 is enabled.
     *
     * @param bool $ssl3Enabled
     *
     * @return self
     */
    public function setSsl3Enabled(?bool $ssl3Enabled): self
    {
        $this->ssl3Enabled = $ssl3Enabled;

        return $this;
    }

    /**
     * Gets or sets invalid certificate action for the target URL.
     *
     * @return string
     */
    public function getTargetUrlInvalidCertificateAction(): ?string
    {
        return $this->targetUrlInvalidCertificateAction;
    }

    /**
     * Gets or sets invalid certificate action for the target URL.
     *
     * @param string $targetUrlInvalidCertificateAction
     *
     * @return self
     */
    public function setTargetUrlInvalidCertificateAction(?string $targetUrlInvalidCertificateAction): self
    {
        $this->targetUrlInvalidCertificateAction = $targetUrlInvalidCertificateAction;

        return $this;
    }

    /**
     * Gets or sets a value indicating whether TLS 1.0 is enabled.
     *
     * @return bool
     */
    public function getTls10Enabled(): ?bool
    {
        return $this->tls10Enabled;
    }

    /**
     * Gets or sets a value indicating whether TLS 1.0 is enabled.
     *
     * @param bool $tls10Enabled
     *
     * @return self
     */
    public function setTls10Enabled(?bool $tls10Enabled): self
    {
        $this->tls10Enabled = $tls10Enabled;

        return $this;
    }

    /**
     * Gets or sets a value indicating whether TLS 1.1 is enabled.
     *
     * @return bool
     */
    public function getTls11Enabled(): ?bool
    {
        return $this->tls11Enabled;
    }

    /**
     * Gets or sets a value indicating whether TLS 1.1 is enabled.
     *
     * @param bool $tls11Enabled
     *
     * @return self
     */
    public function setTls11Enabled(?bool $tls11Enabled): self
    {
        $this->tls11Enabled = $tls11Enabled;

        return $this;
    }

    /**
     * Gets or sets a value indicating whether TLS 1.2 is enabled.
     *
     * @return bool
     */
    public function getTls12Enabled(): ?bool
    {
        return $this->tls12Enabled;
    }

    /**
     * Gets or sets a value indicating whether TLS 1.2 is enabled.
     *
     * @param bool $tls12Enabled
     *
     * @return self
     */
    public function setTls12Enabled(?bool $tls12Enabled): self
    {
        $this->tls12Enabled = $tls12Enabled;

        return $this;
    }
}
