<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class UrlRewriteRuleModel
{
    /**
     * Gets or sets the path placeholders.
     *
     * @var string
     */
    protected $placeholderPattern;
    /**
     * Gets or sets the pattern.
     *
     * @var string
     */
    protected $regexPattern;

    /**
     * Gets or sets the path placeholders.
     *
     * @return string
     */
    public function getPlaceholderPattern(): ?string
    {
        return $this->placeholderPattern;
    }

    /**
     * Gets or sets the path placeholders.
     *
     * @param string $placeholderPattern
     *
     * @return self
     */
    public function setPlaceholderPattern(?string $placeholderPattern): self
    {
        $this->placeholderPattern = $placeholderPattern;

        return $this;
    }

    /**
     * Gets or sets the pattern.
     *
     * @return string
     */
    public function getRegexPattern(): ?string
    {
        return $this->regexPattern;
    }

    /**
     * Gets or sets the pattern.
     *
     * @param string $regexPattern
     *
     * @return self
     */
    public function setRegexPattern(?string $regexPattern): self
    {
        $this->regexPattern = $regexPattern;

        return $this;
    }
}
