<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class UserHealthCheckApiModel
{
    /**
     * Gets or sets user's date format.
     *
     * @var string
     */
    protected $dateFormat;
    /**
     * Gets or sets user display name.
     *
     * @var string
     */
    protected $displayName;
    /**
     * Gets or sets Email.
     *
     * @var string
     */
    protected $email;
    /**
     * Gets or sets user's time info.
     *
     * @var string
     */
    protected $timeZoneInfo;

    /**
     * Gets or sets user's date format.
     *
     * @return string
     */
    public function getDateFormat(): ?string
    {
        return $this->dateFormat;
    }

    /**
     * Gets or sets user's date format.
     *
     * @param string $dateFormat
     *
     * @return self
     */
    public function setDateFormat(?string $dateFormat): self
    {
        $this->dateFormat = $dateFormat;

        return $this;
    }

    /**
     * Gets or sets user display name.
     *
     * @return string
     */
    public function getDisplayName(): ?string
    {
        return $this->displayName;
    }

    /**
     * Gets or sets user display name.
     *
     * @param string $displayName
     *
     * @return self
     */
    public function setDisplayName(?string $displayName): self
    {
        $this->displayName = $displayName;

        return $this;
    }

    /**
     * Gets or sets Email.
     *
     * @return string
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Gets or sets Email.
     *
     * @param string $email
     *
     * @return self
     */
    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Gets or sets user's time info.
     *
     * @return string
     */
    public function getTimeZoneInfo(): ?string
    {
        return $this->timeZoneInfo;
    }

    /**
     * Gets or sets user's time info.
     *
     * @param string $timeZoneInfo
     *
     * @return self
     */
    public function setTimeZoneInfo(?string $timeZoneInfo): self
    {
        $this->timeZoneInfo = $timeZoneInfo;

        return $this;
    }
}
