<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class WebsiteApiModel
{
    /**
     * Gets or sets the website identifier.
     *
     * @var string
     */
    protected $id;
    /**
     * Gets or sets the date which this website was created at.
     *
     * @var \DateTime
     */
    protected $createdAt;
    /**
     * Gets or sets the date which this website was updated at.
     *
     * @var \DateTime
     */
    protected $updatedAt;
    /**
     * Gets or sets the root domain URL.
     *
     * @var string
     */
    protected $rootUrl;
    /**
     * Gets or sets a name for this website.
     *
     * @var string
     */
    protected $name;
    /**
     * Gets or sets the name of groups this website will belong to.
     *
     * @var IdNamePair[]
     */
    protected $groups;
    /**
     * Gets or sets a value indicating whether this website is verified.
     *
     * @var bool
     */
    protected $isVerified;
    /**
     * Gets or sets the type of the subscription.
     *
     * @var string
     */
    protected $licenseType;
    /**
     * Gets or sets the agent mode.
     *
     * @var string
     */
    protected $agentMode;

    /**
     * Gets or sets the website identifier.
     *
     * @return string
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Gets or sets the website identifier.
     *
     * @param string $id
     *
     * @return self
     */
    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets or sets the date which this website was created at.
     *
     * @return \DateTime
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * Gets or sets the date which this website was created at.
     *
     * @param \DateTime $createdAt
     *
     * @return self
     */
    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Gets or sets the date which this website was updated at.
     *
     * @return \DateTime
     */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    /**
     * Gets or sets the date which this website was updated at.
     *
     * @param \DateTime $updatedAt
     *
     * @return self
     */
    public function setUpdatedAt(?\DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Gets or sets the root domain URL.
     *
     * @return string
     */
    public function getRootUrl(): ?string
    {
        return $this->rootUrl;
    }

    /**
     * Gets or sets the root domain URL.
     *
     * @param string $rootUrl
     *
     * @return self
     */
    public function setRootUrl(?string $rootUrl): self
    {
        $this->rootUrl = $rootUrl;

        return $this;
    }

    /**
     * Gets or sets a name for this website.
     *
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Gets or sets a name for this website.
     *
     * @param string $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets or sets the name of groups this website will belong to.
     *
     * @return IdNamePair[]
     */
    public function getGroups(): ?array
    {
        return $this->groups;
    }

    /**
     * Gets or sets the name of groups this website will belong to.
     *
     * @param IdNamePair[] $groups
     *
     * @return self
     */
    public function setGroups(?array $groups): self
    {
        $this->groups = $groups;

        return $this;
    }

    /**
     * Gets or sets a value indicating whether this website is verified.
     *
     * @return bool
     */
    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    /**
     * Gets or sets a value indicating whether this website is verified.
     *
     * @param bool $isVerified
     *
     * @return self
     */
    public function setIsVerified(?bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * Gets or sets the type of the subscription.
     *
     * @return string
     */
    public function getLicenseType(): ?string
    {
        return $this->licenseType;
    }

    /**
     * Gets or sets the type of the subscription.
     *
     * @param string $licenseType
     *
     * @return self
     */
    public function setLicenseType(?string $licenseType): self
    {
        $this->licenseType = $licenseType;

        return $this;
    }

    /**
     * Gets or sets the agent mode.
     *
     * @return string
     */
    public function getAgentMode(): ?string
    {
        return $this->agentMode;
    }

    /**
     * Gets or sets the agent mode.
     *
     * @param string $agentMode
     *
     * @return self
     */
    public function setAgentMode(?string $agentMode): self
    {
        $this->agentMode = $agentMode;

        return $this;
    }
}
