<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Montross50\NetsparkerCloud\SDK\Model;

class WebsiteGroupModel
{
    /**
     * Gets the display name.
     *
     * @var string
     */
    protected $displayName;
    /**
     * Gets or sets the group identifier.
     *
     * @var string
     */
    protected $id;
    /**
     * Gets or sets the group name.
     *
     * @var string
     */
    protected $name;
    /**
     * Gets or sets the not verified website count.
     *
     * @var int
     */
    protected $notVerifiedWebsiteCount;
    /**
     * Gets or sets the verified website count.
     *
     * @var int
     */
    protected $verifiedWebsiteCount;

    /**
     * Gets the display name.
     *
     * @return string
     */
    public function getDisplayName(): ?string
    {
        return $this->displayName;
    }

    /**
     * Gets the display name.
     *
     * @param string $displayName
     *
     * @return self
     */
    public function setDisplayName(?string $displayName): self
    {
        $this->displayName = $displayName;

        return $this;
    }

    /**
     * Gets or sets the group identifier.
     *
     * @return string
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Gets or sets the group identifier.
     *
     * @param string $id
     *
     * @return self
     */
    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets or sets the group name.
     *
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Gets or sets the group name.
     *
     * @param string $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets or sets the not verified website count.
     *
     * @return int
     */
    public function getNotVerifiedWebsiteCount(): ?int
    {
        return $this->notVerifiedWebsiteCount;
    }

    /**
     * Gets or sets the not verified website count.
     *
     * @param int $notVerifiedWebsiteCount
     *
     * @return self
     */
    public function setNotVerifiedWebsiteCount(?int $notVerifiedWebsiteCount): self
    {
        $this->notVerifiedWebsiteCount = $notVerifiedWebsiteCount;

        return $this;
    }

    /**
     * Gets or sets the verified website count.
     *
     * @return int
     */
    public function getVerifiedWebsiteCount(): ?int
    {
        return $this->verifiedWebsiteCount;
    }

    /**
     * Gets or sets the verified website count.
     *
     * @param int $verifiedWebsiteCount
     *
     * @return self
     */
    public function setVerifiedWebsiteCount(?int $verifiedWebsiteCount): self
    {
        $this->verifiedWebsiteCount = $verifiedWebsiteCount;

        return $this;
    }
}
